# Numpy exercices pratiques
Ce notebook à pour objectif de vous faire pratiquer numpy dans toute sa généralité. 
Vous avez donc une liste de questions à faire ! Il ne faut pas hésiter à faire des recherches sur google ainsi que voir la [documentation officielle](https://docs.scipy.org/doc/numpy-1.13.0/reference/). 

#### Q1 : Importer le package numpy 

In [2]:
import numpy as np

#### Q2 : Afficher la version de numpy et la configuration 

In [4]:
np.version.version

'1.19.2'

In [43]:
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Simon/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Simon/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Simon/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Simon/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Simon/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Simon/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Simon/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Simon/anaconda3\\Library\\include']


#### Q3 : Créer un vecteur nul de taille 10

In [9]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Q4 : Créer un vecteur null de taille 10 et affecter la valeur 1 à la 4ème place (index 4) du vecteur

In [13]:
vec = np.zeros(10)
vec[4] = 1
vec

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### Q5 : Créer un vecteur Z de 40 valeurs allant de 10 à 50 

In [17]:
Z = np.arange(10, 51)
Z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Q6 : Inverser Z (le premier élément devient donc le dernier)

In [23]:
np.flipud(Z)

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10])

#### Q7 : Créer une matrice 3x3 avec des valeurs comprise entre 0 et 8 

In [26]:
mat = np.arange(9)
mat = mat.reshape(3,3)
mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Q8 : Créer une matrice identié 3x3 

In [27]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Q9 : Créer une matrice 3x3x3 avec des valeurs random 

In [41]:
np.random.rand(3,3,3)

array([[[0.48744016, 0.02119413, 0.17585973],
        [0.28168353, 0.28092399, 0.0330592 ],
        [0.06499207, 0.89405153, 0.74482383]],

       [[0.32454693, 0.54918815, 0.58760343],
        [0.60067116, 0.75256756, 0.94871992],
        [0.63781281, 0.88203285, 0.40226038]],

       [[0.81740825, 0.14040429, 0.18840162],
        [0.83568555, 0.57536078, 0.58752166],
        [0.55762481, 0.97364939, 0.86791428]]])

#### Q10 : Créer une matrice 10x10 avec des valeurs random et afficher le minimum et maximum de cette matrice

In [56]:
mat10 = np.random.rand(10, 10)
mat10.min()
mat10.max()

0.9998724869374179

#### Q11 : Créer une matrice 5x5 avec les valeurs 1,2,3,4 en dessous de la diagonale 

In [59]:
np.diag(1+np.arange(4), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### Q12 : Créer une liste random de taille 5 et donner la somme de ses éléments  

In [3]:
listR = np.random.rand(5)
listR.sum()

1.7286432193120964

#### Q13 : Créer une liste random de taille 5 et donner la moyenne de ses éléments

In [61]:
np.average(listR)

0.7133496898162945

#### Q14 : En utilisant une fonction, donner la taille de la liste suivante :


In [64]:
l = [x for x in range(11)]
np.size(l)

11

#### Q15 : Créer un tableau de taille 10 avec des valeurs comprises entre 0 et 1 EXCLUS 

In [67]:
tab10 = np.linspace(0,1,11,endpoint=False)[1:]
tab10

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### Q16 : Soit deux tableau A et B de dimension 1 et de taille 5, créer A et B et afficher True si A et B sont égaux False sinon

In [68]:
tabA = [1, 2, 3, 4, 5]
tabB = np.flip(tabA)
np.array_equal(tabA, tabB)

False

#### Q17 : Convertir un tableau de float32 de dimension 1 et de taille 10 en un tableau de meme taille et dimension mais de type int32

#### Q18 : Normaliser une matrice random 5x5 
La normalisation d'un nombre X consiste à lui retirer sa moyenne et a diviser le tout par son écart type 

In [11]:
matR5 = np.random.random(5)
norm = np.linalg.norm(matR5)

NameError: name 'v' is not defined

#### Q19 : Créer une matrice random `M` 2x2 et donner sa transposer 
L'opération de transposition dans une matrice consiste à échanger les lignes et le colonnes. 

#### Q20 : Écrire un petit script qui remplace un élément au hasard dans une matrice de dimension NxN

#### Q21 : Considérons une matrice de dimension (5,5,3), écrire un script qui multiplie cette matrice par une matrice de dimension (5,5)